### ISSUE TITLE
Admin pages issues

### ISSUE THREAD

**Issue by Zorrototo** [OpenGamePanel/Theme-Metro#2]
Admin/all pages for the core or the extra modules have an horizontal scroll bar at bottom of the page.

**Comment by DieFeM** [comment]
I can't see it, I guess a browser specific issue, what browser you use?

**Comment by DieFeM** [comment]
I've found it in edge, I fixed it there by changing the line 128 of style.css
From : 
padding-right:1%;
To:
padding-right:21px;

Try it in your browser, if it fixes the problem then I will change it.

**Comment by Zorrototo** [comment]
Yes.

 Fixed also by 

> .main-content {
>     background: #FFF;
>     overflow: auto;
>     padding: 1.1%;
> }

**Comment by DieFeM** [comment]
I've been testing it, and it still shows if you do the window smaller. But this one works pretty good, I' ll apply it.

```
.main-content {
	background:#FFF;
	overflow:hidden;
}
```

**Comment by Zorrototo** [comment]
:+1: 

page /home.php?m=dashboard&p=dashboard still messed up, It has extremely large page (Dashboard and Status installed)

**Comment by DieFeM** [comment]
Edge: https://prnt.sc/keo866
Chrome: https://prnt.sc/keo8k0

I can't see it, what browser?

**Comment by Zorrototo** [comment]
Firefox
